### ISSUE TITLE
Windows + busybox

### ISSUE THREAD

**Issue by pocomane** [skywind3000/asyncrun.vim#101]
I can not use AsyncRun because:

- I am under windows, but I do not use cmd.exe as shell
- More than one flag is specified into shellcmdflag

For now, my quick and dirty solution is:

```
216,217c216,217
<       let s:asyncrun_windows = 1
<       let g:asyncrun_windows = 1
---
>       let s:asyncrun_windows = 0
>       let g:asyncrun_windows = 0
588c588
<               let l:args = [&shell, &shellcmdflag]
---
>               let l:args = [&shell] + split(&shellcmdflag)
```

**Comment by skywind3000** [comment]
no need to change the source code, just set:

g:asyncrun_shell - as shell
g:asyncrun_shellflag - as shellcmdflag

**Comment by skywind3000** [comment]
sorry, I forget you are running on windows. the .cmd file is required because job_start cannot pass arguments correctly on windows when arguments contain punctuations like `"` and `'`.

I still don't recomment modifying the code, because you have to merge new versions yourself in the future.

AsyncRun have two way to achieve this:

first: use `powershell -command ...`

```VimL
:AsyncRun powershell -command echo 1 2 3
```

second: setup `g:asyncrun_wrapper` in your vimrc:

```VimL
set g:asyncrun_wrapper = 'powershell -command'
```

the `g:asyncrun_wrapper` will setup a command prefix.

**Comment by pocomane** [comment]
I did not find asyncrun_wrapper in the documentation but with a quick look at the code I find a way to let it work:

```
let g:asyncrun_shell='cmd.exe'
let g:asyncrun_shellflag='/C'
let g:asyncrun_wrapper = 'busybox ash -c'
```

Or more generally:

```
let g:asyncrun_shell='cmd.exe'
let g:asyncrun_shellflag='/C'
let g:asyncrun_wrapper = &shell . ' ' . &shellcmdflag
```

However I still think that shellcmdflag could be handled in a better way. I hope to make some test on linux in the next days and I will open a dedicated issue if I think it is appropiate.

Thanks for the help!

**Comment by skywind3000** [comment]
`g:asyncrun_wrapper` was just introduced three days earlier and was undocumented yet.

I just wrote a new wiki page about option details:

https://github.com/skywind3000/asyncrun.vim/wiki/Options
