### ISSUE TITLE
Wishlist: g:asynrun_start callback

### ISSUE THREAD

**Issue by mgedmin** [skywind3000/asyncrun.vim#21]
I would like to change my status line color to indicate the status of the async job:

- green when it's successful
- red when it failed
- purple when it's still running

I can do the first two from the `g:asyncrun_exit` callback.  To do the third, I have to overwrite the `:AsyncRun` command, which is cumbersome to do, since plugins are sourced after my `.vimrc`.

What do you think about adding a `g:asyncrun_start` setting, with a script to be executed right before a job is started?

**Comment by skywind3000** [comment]
nice idea, but just a `g:asyncrun_start` is not enough, I'm not sure what does the `g:asyncrun_start` stand for ? 
- before starting the job ?
- after successfully starting the job ? (because job_start may failed)

So the latest asyncrun provides autocmd instead of `g:asyncrun_start`. That's more adaptive:

```VimL
autocmd User AsyncRunPre   - triggered before executing
autocmd User AsyncRunStart - triggered after starting successfully
autocmd User AsyncRunStop  - triggered when job finished
```

Note, `AsyncRunPre` is always likely to be invoked, but `AsyncRunStart` and `AsyncRunStop` will only be invoked if the job starts successfully. 

When previous job is still running or vim job slot is full, AsyncRun may fail. In this circumstance, `AsyncRunPre` will be invoked but `AsyncRunStart` and `AsyncRunStop` will have no chance to trigger.

with this feature you can change your statusline in a more convenience way:

```VimL
augroup MyAsyncRunCmd
    au!
    au User AsyncRunStart   (make your status line purple)
    au User AsyncRunStop   (make your status line green or red)
augroup END
```

Will it solve your problem ?

**Comment by mgedmin** [comment]
Yes, that will do very well!  Thank you!
