### ISSUE TITLE
AsyncRunStop does not allow to echo message

### ISSUE THREAD

**Issue by tkhai** [skywind3000/asyncrun.vim#57]
Hello!

I want to have a notification when AsyncRun stops execution. I use:
autocmd User AsyncRunStop if g:asyncrun_code != 0 | echohl AsyncRunFail | echo 'AsyncRun: [FAIL]' |
                        \ else | echohl AsyncRunOK | echo 'AsyncRun: [OK]' | endif | echohl Normal

But this does not work as s:AutoCmd raises the event silently. The below change helps me:

function! s:AutoCmd(name)
        if has('autocmd')
"               exec 'silent doautocmd User AsyncRun'.a:name
                exec 'doautocmd User AsyncRun'.a:name
        endif
endfunc

Could you please to allow echo messages in such way? At least, for autocmd's, which are exported to user.

Kirill

**Comment by tkhai** [comment]
Note, that g:asyncrun_exit can't be used for the goal, as it intersects with another plugins (ErrorMarker calls redraw on QuickFixCmdPost).

**Comment by skywind3000** [comment]
Because there is a `silent` in line 183, you can remove it your self, but I suggest not.
sometimes, two `echo`  happen one after another in a short period, will cause your gui scroll up. vim will scroll the whole gui up to make enough space to display two lines in the bottom.

It is a serious disturbance when you are editing. There is two alternative ways to notify you job finish:
1. statusline, use statusline to indicate job progress: I have a `[running]` and a `[finish]` on my statusline, and some users have made their statusline blue for `running` and green for `success`, red for `failure`.
2. play a sound (gvim) or ring the alert (terminal) after job finish, because you are focusing on editing, sound is more effective than a text line below.

**Comment by tkhai** [comment]
No, I like the way I asked in the question. It's more comfortable for me.

Can't user pass silent himself, if it really needs it?

**Comment by skywind3000** [comment]
ok, I have added a new option `g:asyncrun_silent` which is default by 1, you can set it to 0 to disable silent doautocmd .

**Comment by tkhai** [comment]
Thank you, it's really wonderful!!! The best plugin! 👍

I've tested and already updated my vimrc: https://github.com/tkhai/configs/commit/765414309f7f7255c022c189a33c5bb9942efa98

**Comment by skywind3000** [comment]
one more thing , you can use 

```VimL
nosilent echo xxx
```

**Comment by fcying** [comment]
> one more thing , you can use
> 
> ```viml
> nosilent echo xxx
> ```

nosilent  Not an editor command
```
E492: Not an editor command: nosilent echo "ok"
```
`let g:asyncrun_silent = 0` can work
