### ISSUE TITLE
AsyncRun -cwd=<root> doesn't change the current working directory to project root

### ISSUE THREAD

**Issue by bfrg** [skywind3000/asyncrun.vim#87]
I tried one of the examples from the [Project Root](https://github.com/skywind3000/asyncrun.vim/wiki/Project-Root) Wiki page:
```vim
:AsyncRun -cwd=<root> grep -n -R --include=*.hpp  MyClass .
```
I ran the above command while **not** in the project root directory. The quickfix window displayed all files relative to the project root. But the command did **not** change the working directory to project root. So, I have to change the current working directory manually with `:cd ../../../` to the project root directory before I can use the results shown in the quickfix window, otherwise it will open empty buffers.
I don't know if this is intentional or not. The Wiki page says that `AsyncRun` will change the working directory when the option `-cmd=<root>` is used.

**Comment by skywind3000** [comment]
In order to prevent unwanted cwd changing, AsyncRun will just temporarily change the working directory. And it will switch back to previous cwd after calling job_start().

So quickfix can't take care of the relative path names. you may try:

1. get grep output absolute path.

2. try another command like:

```
:AsyncRun grep -n -R --include=*.hpp  MyClass <root>
```

**Comment by bfrg** [comment]
That makes sense. Thanks.
